Gate API-key tests to run only if the necessary secret is not empty

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,7 +32,18 @@ jobs:
         run: poetry run pytest -m "not ncbi" --disable-socket --allow-unix-socket
       - name: Mark unauthorized PR as unrunnable
         if: github.event.pull_request.user != github.repository_owner
-        run: exit 1
+        run: |
+          echo "$USER does not have"
+          exit 1
+        env:
+          USER: ${{github.event.pull_request.user}}
+      - name: Check if NCBI auth is present
+        env:
+          super_secret: ${{ secrets.NCBI_API_KEY }}
+        if: ${{ env.super_secret == '' }}
+        run: |
+          echo "NCBI authentication not provided. Failing out."
+          exit 1
       - name: Run NCBI-dependent tests
         run: poetry run pytest -m "ncbi"
         env:
